# Название workflow, которое отображается в интерфейсе GitHub Actions
name: Terraform CI/CD

# События, которые запускают workflow:
# - push в ветку master (при прямом коммите или мерже)
# - pull_request в ветку master (при создании/обновлении PR)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Глобальные переменные окружения для всех jobs
# TF_VERSION - версия Terraform для использования
env:
  TF_VERSION: 1.5.0

# Секция с перечислением всех задач (jobs), которые будут выполняться
jobs:

  # Первая job - проверка кода Terraform (валидация, форматирование)
  terraform-validation:
    name: Terraform Validation  # Человекочитаемое имя job
    runs-on: ubuntu-latest      # Запуск на последней версии Ubuntu
    
    steps:
    # Шаг 1: Клонирование репозитория на runner
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Установка указанной версии Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Шаг 3: Инициализация Terraform (скачивание провайдеров, настройка backend)
    - name: Terraform Init
      run: terraform init

    # Шаг 4: Проверка синтаксиса конфигурационных файлов Terraform
    - name: Terraform Validate
      run: terraform validate

    # Шаг 5: Проверка форматирования кода без его изменения
    - name: Terraform Format
      run: terraform fmt -check

  # Вторая job - создание плана изменений Terraform
  terraform-plan:
    name: Terraform Plan        # Человекочитаемое имя job
    runs-on: ubuntu-latest      # Запуск на последней версии Ubuntu
    needs: terraform-validation # Выполняется только после успешной валидации
    
    steps:
    # Шаг 1: Клонирование репозитория на runner
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Установка указанной версии Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Шаг 3: Инициализация Terraform с credentials для доступа к remote state
    # (если используется S3 backend или другие провайдеры)
    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Шаг 4: Создание плана изменений
    # -no-color - убирает цвета для лучшего логирования
    # -input=false - отключает интерактивный ввод
    - name: Terraform Plan
      run: terraform plan -no-color -input=false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  # Третья job - применение изменений Terraform
  # ⚠️ ВНИМАНИЕ: Для production рекомендуется добавить manual approval
  terraform-apply:
    name: Terraform Apply       # Человекочитаемое имя job
    runs-on: ubuntu-latest      # Запуск на последней версии Ubuntu
    needs: terraform-plan       # Выполняется только после успешного планирования
    if: github.ref == 'refs/heads/master'  # ТОЛЬКО для ветки master (защита)
    
    steps:
    # Шаг 1: Клонирование репозитория на runner
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Установка указанной версии Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Шаг 3: Инициализация Terraform с credentials для доступа к remote state
    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Шаг 4: Применение изменений автоматически
    # -auto-approve - без ручного подтверждения (ОПАСНО для production!)
    # -input=false - отключает запросы ввода
    # 🔒 Рекомендация: Добавить environment с required reviewers
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
