# Название workflow, которое отображается в интерфейсе GitHub Actions
name: Terraform CI/CD

# События, которые запускают workflow:
# - push в ветку master (при прямом коммите или мерже)
# - pull_request в ветку master (при создании/обновлении PR)
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Глобальные переменные окружения для всех jobs
# TF_VERSION - версия Terraform для использования
# TF_DIR - директория с Terraform кодом (можно изменить под вашу структуру)
env:
  TF_VERSION: 1.5.0
  TF_DIR: 'terraform/main'  # ← Указываем поддиректорию с Terraform кодом

# Секция с перечислением всех задач (jobs), которые будут выполняться
jobs:

  # Первая job - проверка кода Terraform (валидация, форматирование)
  terraform-validation:
    name: Terraform Validation  # Человекочитаемое имя job
    runs-on: ubuntu-latest      # Запуск на последней версии Ubuntu
    
    # Указываем рабочую директорию для всех шагов этой job
    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}  # ← Работаем из поддиректории
    
    steps:
    # Шаг 1: Клонирование репозитория на runner
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Установка указанной версии Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Шаг 3: Инициализация Terraform (скачивание провайдеров, настройка backend)
    - name: Terraform Init
      run: terraform init

    # Шаг 4: Проверка синтаксиса конфигурационных файлов Terraform
    - name: Terraform Validate
      run: terraform validate

    # Шаг 5: Проверка форматирования кода без его изменения
    - name: Terraform Format
      run: terraform fmt -check -recursive  # ← -recursive для проверки всех файлов

    # Шаг 6: Показываем содержимое директории для отладки
    - name: List files in Terraform directory
      run: ls -la
      working-directory: ${{ env.TF_DIR }}  # ← Показываем файлы в terraform/

  # Вторая job - создание плана изменений Terraform
  terraform-plan:
    name: Terraform Plan        # Человекочитаемое имя job
    runs-on: ubuntu-latest      # Запуск на последней версии Ubuntu
    needs: terraform-validation # Выполняется только после успешной валидации
    
    # Указываем рабочую директорию для всех шагов этой job
    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}  # ← Работаем из поддиректории
    
    steps:
    # Шаг 1: Клонирование репозитория на runner
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Установка указанной версии Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Шаг 3: Инициализация Terraform с credentials для доступа к remote state
    # (если используется S3 backend или другие провайдеры)
    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Шаг 4: Создание плана изменений
    # -no-color - убирает цвета для лучшего логирования
    # -input=false - отключает интерактивный ввод
    - name: Terraform Plan
      run: terraform plan -no-color -input=false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Шаг 5: Сохраняем план для использования в apply job
    - name: Save Terraform Plan
      run: terraform plan -no-color -input=false -out=tfplan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Шаг 6: Загружаем артефакт плана (опционально)
    - name: Upload Terraform Plan
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: ${{ env.TF_DIR }}/tfplan

  # Третья job - применение изменений Terraform
  # ⚠️ ВНИМАНИЕ: Для production рекомендуется добавить manual approval
  terraform-apply:
    name: Terraform Apply       # Человекочитаемое имя job
    runs-on: ubuntu-latest      # Запуск на последней версии Ubuntu
    needs: terraform-plan       # Выполняется только после успешного планирования
    if: github.ref == 'refs/heads/master'  # ТОЛЬКО для ветки master (защита)
    
    # Указываем рабочую директорию для всех шагов этой job
    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}  # ← Работаем из поддиректории
    
    steps:
    # Шаг 1: Клонирование репозитория на runner
    - name: Checkout code
      uses: actions/checkout@v4

    # Шаг 2: Загружаем артефакт плана (если использовали upload)
    - name: Download Terraform Plan
      uses: actions/download-artifact@v3
      with:
        name: terraform-plan
        path: ${{ env.TF_DIR }}

    # Шаг 3: Установка указанной версии Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TF_VERSION }}

    # Шаг 4: Инициализация Terraform с credentials для доступа к remote state
    - name: Terraform Init
      run: terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    # Шаг 5: Применение изменений автоматически
    # -auto-approve - без ручного подтверждения (ОПАСНО для production!)
    # -input=false - отключает запросы ввода
    # 🔒 Рекомендация: Добавить environment с required reviewers
    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
